/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/agent/query": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 图谱问答
         * @description 单轮问答 + 可溯源引用。每个事实句必须能回溯到 `citations[]`，引用覆盖率不足时**必须拒答**（`refused = true`），严禁编造引用（M3 验收 3）。
         *
         *     `refused = true` 时 `answer` 恒为 `无法回答`。
         *
         *     **版本一致性（ADR-0002 §3.2）**：显式传入非 active 的 `kg_version` 时一律返回 **409** `KG_VERSION_NOT_ACTIVE`，**严禁静默降级**。
         *
         *     **实现状态**：已实装——由 `AgentService.query`（`app/services/agents.py`）执行「取 active 版本 → 拉取相关子图 → 加载 `kg_qa` Prompt → LLM 调用与解析」单轮链路，返回 `AgentQueryResponse`。
         *
         *     **501 `NOT_IMPLEMENTED` 的真实语义**：LLM 未配置（`DEEPSEEK_API_KEY` 缺失）/ LangChain 装配失败 / Neo4j 不可用时返回 501，表示**基础设施不可用**，**不**表示「接口未实现」。
         */
        post: operations["queryAgent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 上传文档（异步受理）
         * @description **同步校验 + 立即返回**，不在请求内做任何解析：
         *     1. MIME 白名单校验 → 失败 415；
         *     2. 大小上限校验（默认 100MB）→ 失败 413；
         *     3. 落 `documents` 记录（`status = pending`），注册 `document.parse` 异步执行体，并返回 `task_id`。
         *
         *     **解析链路**：执行体真实推进 `pending → processing → completed / failed`（M1 硬约束 H1），第三方 IO 异常按 H8 指数退避重试（≤ 3 次）；进程重启时由启动回收把在途任务置 `failed` + `error_code = TASK_INTERRUPTED`（ADR-0001 §3.2）。
         *
         *     上传响应的 `status` 恒为 `pending`，后续进度请轮询 `GET /documents/{id}/status`。
         *
         *     **当前局限**：状态机与错误落库为真实链路；MinerU 结构化解析与 LangExtract 实体关系抽取尚未接入，执行体当前返回空结果（后续版本补齐，见 v1.1.0 待办）。
         *
         *     文件名以 SHA-256 落库（`filename_hash`），日志与响应均不含原文。
         */
        post: operations["uploadDocument"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents/{document_id}/graph": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 获取文档图谱子图
         * @description 返回该文档在 Neo4j 中的子图（`nodes` + `edges`），供前端力导向图渲染。
         *
         *     **一致性（ADR-0002 §3.2）**：只返回 `status = active` 的 `kg_version`；该文档不存在 active 版本时返回 **409** `KG_VERSION_NOT_ACTIVE`，**绝不静默降级**到其他版本；响应中的 `version_status` 恒为 `active`。
         *
         *     规模上限对齐 M3 §3 验收 1：单次节点数 ≤ 500，超限 `truncated = true`。
         *
         *     **实现状态**：已实装——由 `GraphService.fetch_document_subgraph`（`app/services/graphs.py`）按 `kg_version` 查询 Neo4j 子图，并映射为 `DocumentGraphResponse`（`nodes` / `edges` / `truncated` / `version_status`）。
         *
         *     **501 `NOT_IMPLEMENTED` 的真实语义**：Neo4j 不可用（连接失败 / 查询超时 / 凭据错误）属**基础设施故障**，此时返回 501——**不**表示「接口未实现」。
         */
        get: operations["getDocumentGraph"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents/{document_id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 查询文档解析状态
         * @description 状态机严格限定为 `pending → processing → completed / failed`（M1 硬约束 H1）。
         *
         *     轮询建议：首次 2s，3 次后降为 10s。
         *
         *     **跨租户访问返回 403**（`FORBIDDEN`），不返回 404——按 M5 §3 验收 1 的显式要求。
         */
        get: operations["getDocumentStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 健康检查（豁免租户上下文）
         * @description 不要求认证、不返回任何业务数据。
         *
         *     依赖异常时仍返回 **200**，仅把 `status` 降级为 `degraded`，避免负载均衡因单实例依赖抖动直接摘除全部流量。
         */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AgentQueryRequest
         * @description `POST /api/v1/agent/query` 请求体（M3 §4.1）。
         * @example {
         *       "kg_version": "20260320T1430Z-01H9X9ABCDEF",
         *       "question": "A 公司的子公司的供应商是否同时是 B 公司的股东？",
         *       "scope": "cross_doc"
         *     }
         */
        AgentQueryRequest: {
            /**
             * Doc Id
             * @description 限定文档 id，仅 `scope = single_doc` 时使用
             */
            doc_id?: string | null;
            /**
             * Kg Version
             * @description 指定图谱版本，缺省取最新 active 版本。若指定版本的 status ≠ active（writing / failed / superseded），一律返回 409 KG_VERSION_NOT_ACTIVE，严禁静默降级（ADR-0002 §3.2）
             */
            kg_version?: string | null;
            /**
             * Question
             * @description 用户问题（单轮，不做多轮上下文）
             */
            question: string;
            /**
             * Scope
             * @description 检索范围；`single_doc` 时 `doc_id` 必填
             * @default cross_doc
             * @enum {string}
             */
            scope: "single_doc" | "cross_doc";
        };
        /**
         * AgentQueryResponse
         * @description `POST /api/v1/agent/query` 响应（M3 §4.2）。
         *
         *     Sprint 4 阶段 10.0 批次 A 扩展（Sprint 3 缺口 1 偿还）：
         *     新增 ``kg_nodes`` / ``kg_relations`` / ``token_usage`` 三字段，
         *     供前端 p03「引用证据」面板展示图谱证据与 token 用量。
         * @example {
         *       "answer": "是。示例子公司 A 的供应商 C 同时持有 B 公司 12% 股权 [source: doc-9/page-3/chunk-12]",
         *       "citations": [
         *         {
         *           "char_offset": 480,
         *           "chunk_id": "chunk-12",
         *           "doc_id": "3f1a9c2e-7b45-4d8a-9e01-2c4f6a8b0d11",
         *           "page": 3,
         *           "snippet": "……供应商 C 持有本公司 12% 股权……"
         *         }
         *       ],
         *       "confidence": "high",
         *       "kg_nodes": [
         *         {
         *           "canonical_name": "示例科技有限公司",
         *           "confidence": 0.93,
         *           "entity_type": "公司",
         *           "id": "e-001",
         *           "kg_version": "20260320T1430Z-01H9X9ABCDEF",
         *           "label": "Entity"
         *         }
         *       ],
         *       "kg_relations": [
         *         {
         *           "id": "r-001",
         *           "properties": {
         *             "share_pct": 51
         *           },
         *           "source": "e-001",
         *           "target": "e-002",
         *           "type": "AFFILIATED_WITH"
         *         }
         *       ],
         *       "kg_version": "20260320T1430Z-01H9X9ABCDEF",
         *       "refused": false,
         *       "route": "m3_graphqa",
         *       "token_usage": {
         *         "completion_tokens": 256,
         *         "prompt_tokens": 2048,
         *         "total_tokens": 2304
         *       },
         *       "trace_id": "5f2c1b7e-9d4a-4c1e-8f3b-6a0d2e5c7b91"
         *     }
         */
        AgentQueryResponse: {
            /**
             * Answer
             * @description 答案文本，含 `[source: ...]` 标记；拒答时恒为 `"无法回答"`
             */
            answer: string;
            /**
             * Citations
             * @description 引用列表；`refused = false` 时必须覆盖全部事实句（覆盖率 100%）
             */
            citations: components["schemas"]["Citation"][];
            /**
             * Confidence
             * @description `low` 时前端必须标记「建议人工复核」（M3 §3 验收 6）
             * @enum {string}
             */
            confidence: "high" | "medium" | "low";
            /**
             * Kg Nodes
             * @description 支撑本次答案的图谱节点（复用 `DocumentGraphResponse.nodes` 同构模型）；拒答 / 图谱为空时为空列表
             */
            kg_nodes?: components["schemas"]["GraphNode"][];
            /**
             * Kg Relations
             * @description 支撑本次答案的图谱关系（复用 `DocumentGraphResponse.edges` 同构模型）；拒答 / 图谱为空时为空列表
             */
            kg_relations?: components["schemas"]["GraphEdge"][];
            /**
             * Kg Version
             * @description 本次检索实际使用的图谱版本（必为 active）
             */
            kg_version: string;
            /**
             * Refusal Reason
             * @description 仅 `refused = true` 时非空
             */
            refusal_reason?: ("no_grounded_evidence" | "out_of_scope" | "low_confidence") | null;
            /**
             * Refused
             * @description 是否拒答（严禁 LLM 编造引用，M3 §3 验收 3）
             */
            refused: boolean;
            /**
             * Route
             * @description 意图路由结果；`m4_affiliation` 表示已转交 M4 场景识别
             * @enum {string}
             */
            route: "m3_graphqa" | "m4_affiliation";
            /** @description LLM token 用量；拒答分支未调用 LLM、或 LLM 未返回 usage 时为 `null` */
            token_usage?: components["schemas"]["TokenUsage"] | null;
            /** Trace Id */
            trace_id: string;
        };
        /** Body_uploadDocument */
        Body_uploadDocument: {
            /**
             * File
             * @description 待解析文件。白名单：PDF / DOCX / CSV；单文件 ≤ 100MB
             */
            file: string;
        };
        /**
         * Citation
         * @description 引用条目：答案的每一个事实句都必须能回溯到此结构（M3 §4.2）。
         *
         *     引用覆盖率必须为 100%，否则必须拒答（反证条件 F3）。
         */
        Citation: {
            /**
             * Char Offset
             * @description 原文 span 在 chunk 内的字符偏移
             */
            char_offset: number;
            /** Chunk Id */
            chunk_id: string;
            /**
             * Doc Id
             * Format: uuid
             */
            doc_id: string;
            /**
             * Page
             * @description 页码（1-based）
             */
            page: number;
            /**
             * Snippet
             * @description 用于 UI 高亮的原文片段
             */
            snippet: string;
        };
        /**
         * DocumentError
         * @description `documents.status = failed` 时的失败信息。
         *
         *     与顶层 `ErrorResponse` 的区别：这里**不含** `trace_id`，
         *     因为响应体已在外层携带同一个 `trace_id`。
         */
        DocumentError: {
            /** @description 失败错误码。进程重启回收的场景为 `TASK_INTERRUPTED`（ADR-0001 §3.2） */
            code: components["schemas"]["ErrorCode"];
            /**
             * Detail
             * @description 失败明细摘要。**禁止**回显 `documents.error_detail` 原文（敏感）
             */
            detail?: {
                [key: string]: unknown;
            } | null;
            /** Message */
            message: string;
        };
        /**
         * DocumentGraphResponse
         * @description `GET /api/v1/documents/{id}/graph` 响应：该文档在 Neo4j 中的子图。
         *
         *     **一致性约束（ADR-0002 §3.2）**：只返回 `status = active` 的 `kg_version`；
         *     该文档无 active 版本时返回 `409 KG_VERSION_NOT_ACTIVE`，**绝不静默降级**到其他版本。
         *
         *     规模上限对齐 M3 §3 验收 1：单次返回节点数 ≤ 500，超限时 `truncated = true`。
         * @example {
         *       "doc_id": "3f1a9c2e-7b45-4d8a-9e01-2c4f6a8b0d11",
         *       "edges": [
         *         {
         *           "id": "r-001",
         *           "properties": {
         *             "share_pct": 51,
         *             "since": "2021-03-01"
         *           },
         *           "source": "e-001",
         *           "target": "e-002",
         *           "type": "AFFILIATED_WITH"
         *         }
         *       ],
         *       "kg_version": "20260320T1430Z-01H9X9ABCDEF",
         *       "node_count": 1,
         *       "nodes": [
         *         {
         *           "canonical_name": "示例科技有限公司",
         *           "confidence": 0.93,
         *           "entity_type": "公司",
         *           "id": "e-001",
         *           "kg_version": "20260320T1430Z-01H9X9ABCDEF",
         *           "label": "Entity"
         *         }
         *       ],
         *       "relation_count": 1,
         *       "trace_id": "5f2c1b7e-9d4a-4c1e-8f3b-6a0d2e5c7b91",
         *       "truncated": false,
         *       "version_status": "active"
         *     }
         */
        DocumentGraphResponse: {
            /**
             * Doc Id
             * Format: uuid
             */
            doc_id: string;
            /** Edges */
            edges: components["schemas"]["GraphEdge"][];
            /**
             * Kg Version
             * @description 本次返回的图谱版本，来自 `GET /internal/kg/active` 的 active 版本
             */
            kg_version: string;
            /**
             * Node Count
             * @description `nodes` 实际条数（截断后）
             */
            node_count: number;
            /** Nodes */
            nodes: components["schemas"]["GraphNode"][];
            /**
             * Relation Count
             * @description `edges` 实际条数（截断后）
             */
            relation_count: number;
            /** Trace Id */
            trace_id: string;
            /**
             * Truncated
             * @description 是否因超过 500 节点上限被截断
             * @default false
             */
            truncated: boolean;
            /**
             * Version Status
             * @description 恒为 `active`，是 ADR-0002 一致性强制的可见契约
             * @constant
             */
            version_status: "active";
        };
        /**
         * DocumentStatusResponse
         * @description `GET /api/v1/documents/{id}/status` 响应（M1 验收 5）。
         *
         *     前端轮询建议：首次 2s，3 次后降为 10s。
         * @example {
         *       "status": "processing",
         *       "task_id": "3f1a9c2e-7b45-4d8a-9e01-2c4f6a8b0d11",
         *       "trace_id": "5f2c1b7e-9d4a-4c1e-8f3b-6a0d2e5c7b91"
         *     }
         */
        DocumentStatusResponse: {
            /** @description 仅当 `status = failed` 时非空 */
            error?: components["schemas"]["DocumentError"] | null;
            /**
             * Progress
             * @description 0–1 的粗粒度进度。解析进度不可精确估计时为 `null`（Sprint 1 恒为 null）
             */
            progress?: number | null;
            /**
             * Status
             * @description 仅取 `pending / processing / completed / failed`（H1）
             * @enum {string}
             */
            status: "pending" | "processing" | "completed" | "failed";
            /**
             * Task Id
             * Format: uuid
             */
            task_id: string;
            /** Trace Id */
            trace_id: string;
        };
        /**
         * ErrorCode
         * @description 统一业务错误码。HTTP 状态码与业务错误码分离（CODEBUDDY.md 错误响应规范）。
         * @enum {string}
         */
        ErrorCode: "VALIDATION_ERROR" | "UNAUTHORIZED" | "FORBIDDEN" | "NOT_FOUND" | "DOCUMENT_NOT_FOUND" | "FILE_TOO_LARGE" | "UNSUPPORTED_MEDIA_TYPE" | "KG_VERSION_NOT_ACTIVE" | "TASK_INTERRUPTED" | "NOT_IMPLEMENTED" | "INTERNAL_ERROR" | "HTTP_ERROR";
        /**
         * ErrorResponse
         * @description 统一错误响应体（**所有** 4xx / 5xx 均使用本结构）。
         *
         *     来源：`CODEBUDDY.md`「错误响应规范」。
         * @example {
         *       "code": "KG_VERSION_NOT_ACTIVE",
         *       "detail": {
         *         "kg_version": "20260320T1430Z-01H9X9",
         *         "version_status": "writing"
         *       },
         *       "message": "Requested kg_version is not active",
         *       "trace_id": "5f2c1b7e-9d4a-4c1e-8f3b-6a0d2e5c7b91"
         *     }
         */
        ErrorResponse: {
            /**
             * @description 业务错误码（HTTP 状态码与业务错误码分离）
             * @example VALIDATION_ERROR
             * @example FORBIDDEN
             * @example KG_VERSION_NOT_ACTIVE
             */
            code: components["schemas"]["ErrorCode"];
            /**
             * Detail
             * @description 结构化补充信息；敏感字段（文件名原文 / error_detail / pii_flags）严禁出现在此
             */
            detail?: {
                [key: string]: unknown;
            } | null;
            /**
             * Message
             * @description 面向调用方的简短英文摘要，便于日志检索
             */
            message: string;
            /**
             * Trace Id
             * @description 与响应头 X-Trace-Id 一致，贯穿 M1–M5 全链路
             */
            trace_id: string;
        };
        /** GraphEdge */
        GraphEdge: {
            /** Id */
            id: string;
            /**
             * Properties
             * @description 关系属性（如 `share_pct` / `since` / `amount` / `role`），不含证据原文
             */
            properties?: {
                [key: string]: unknown;
            };
            /**
             * Source
             * @description 起点节点 id
             */
            source: string;
            /**
             * Target
             * @description 终点节点 id
             */
            target: string;
            /**
             * Type
             * @description 关系类型（M2 §4.2），含桥梁抽取的实体↔实体类关系
             * @enum {string}
             */
            type: "HAS_CHUNK" | "MENTIONS" | "SUPPORTED_BY" | "AFFILIATED_WITH" | "SUPPLIES_TO" | "PARTY_TO" | "HAS_FINANCIAL_INDICATOR" | "OPERATES_SEGMENT" | "RELATED";
        };
        /**
         * GraphNode
         * @description 图谱节点。
         *
         *     **刻意不含** `pii_flags`：M2 §5.3 明确禁止该字段外泄。
         */
        GraphNode: {
            /**
             * Canonical Name
             * @description `:Entity.canonical_name`（消解后的标准名）
             */
            canonical_name?: string | null;
            /**
             * Confidence
             * @description 抽取置信度
             */
            confidence?: number | null;
            /**
             * Entity Type
             * @description `:Entity.type`（公司 / 自然人 / 法人 / 地址 / 证件号等）
             */
            entity_type?: string | null;
            /** Id */
            id: string;
            /**
             * Kg Version
             * @description 节点所属图谱版本，必须等于响应的 `kg_version`
             */
            kg_version: string;
            /**
             * Label
             * @enum {string}
             */
            label: "Document" | "Chunk" | "Entity" | "Evidence";
        };
        /** HealthCheckStatus */
        HealthCheckStatus: {
            /**
             * Database
             * @description 数据库连通性。SQLite 兜底期间仅探测 `SELECT 1`，不代表 RLS 已生效
             * @enum {string}
             */
            database: "up" | "down";
        };
        /**
         * HealthResponse
         * @description 健康检查响应。
         *
         *     **本接口豁免租户上下文**：不要求认证、不返回任何业务数据。
         * @example {
         *       "checks": {
         *         "database": "up"
         *       },
         *       "status": "ok",
         *       "time": "2026-09-16T08:30:00Z",
         *       "trace_id": "5f2c1b7e-9d4a-4c1e-8f3b-6a0d2e5c7b91",
         *       "version": "1.0.0"
         *     }
         */
        HealthResponse: {
            checks: components["schemas"]["HealthCheckStatus"];
            /**
             * Status
             * @description `ok` = 全部依赖正常；`degraded` = 依赖异常但进程可服务（HTTP 仍为 200）
             * @enum {string}
             */
            status: "ok" | "degraded";
            /**
             * Time
             * Format: date-time
             * @description 服务端 UTC 时间
             */
            time: string;
            /** Trace Id */
            trace_id: string;
            /**
             * Version
             * @description 契约版本，与 openapi.yaml 的 info.version 一致
             */
            version: string;
        };
        /**
         * TokenUsage
         * @description LLM token 用量（对齐 DeepSeek / OpenAI 兼容 API 的 `usage` 格式）。
         *
         *     按「实测结果反哺规则」：骨架链路 / LLM 未返回 usage 时，
         *     上层字段 ``AgentQueryResponse.token_usage`` 置 ``null``，**严禁造数据**。
         */
        TokenUsage: {
            /**
             * Completion Tokens
             * @description 输出 token 数
             * @default 0
             */
            completion_tokens: number;
            /**
             * Prompt Tokens
             * @description 输入 token 数
             * @default 0
             */
            prompt_tokens: number;
            /**
             * Total Tokens
             * @description 总 token 数
             * @default 0
             */
            total_tokens: number;
        };
        /**
         * UploadResponse
         * @description `POST /api/v1/documents/upload` 响应（M1 验收 1）。
         * @example {
         *       "status": "pending",
         *       "task_id": "3f1a9c2e-7b45-4d8a-9e01-2c4f6a8b0d11",
         *       "trace_id": "5f2c1b7e-9d4a-4c1e-8f3b-6a0d2e5c7b91"
         *     }
         */
        UploadResponse: {
            /**
             * Status
             * @description 上传受理后恒为 `pending`（异步执行）
             * @constant
             */
            status: "pending";
            /**
             * Task Id
             * Format: uuid
             * @description 任务 id（UUIDv4），与 `documents.id` 一致；M2 抽取任务复用同一 id 空间
             */
            task_id: string;
            /** Trace Id */
            trace_id: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    queryAgent: {
        parameters: {
            query?: never;
            header?: {
                /** @description 【仅开发态兜底】租户 id。仅当 ALLOW_DEV_ORG_HEADER=true 且非生产环境时生效；Sprint 3 接入 M5 登录后必须移除（ADR-0003 §3.3：org_id 严禁来自 body / query）。 */
                "X-Org-Id"?: string | null;
                /** @description 【仅开发态兜底】操作者 id，缺省取 DEFAULT_ACTOR_ID；Sprint 3 起由认证态提供。 */
                "X-Actor-Id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AgentQueryRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentQueryResponse"];
                };
            };
            /** @description 请求校验失败（`VALIDATION_ERROR`），`detail.errors` 给出字段级原因 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 缺少或无法解析认证态（`UNAUTHORIZED`） */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 跨租户访问被拒（`FORBIDDEN`，ADR-0003 §3.3 / M5 §3 验收 1） */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 指定的 `kg_version` 非 active（`KG_VERSION_NOT_ACTIVE`）。**严禁静默降级**到最新 active 版本（ADR-0002 §3.2） */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 基础设施不可用（Neo4j 连接失败 / 查询超时，或 LLM 未配置、装配失败）时返回 501（`NOT_IMPLEMENTED`） */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    uploadDocument: {
        parameters: {
            query?: never;
            header?: {
                /** @description 【仅开发态兜底】租户 id。仅当 ALLOW_DEV_ORG_HEADER=true 且非生产环境时生效；Sprint 3 接入 M5 登录后必须移除（ADR-0003 §3.3：org_id 严禁来自 body / query）。 */
                "X-Org-Id"?: string | null;
                /** @description 【仅开发态兜底】操作者 id，缺省取 DEFAULT_ACTOR_ID；Sprint 3 起由认证态提供。 */
                "X-Actor-Id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_uploadDocument"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadResponse"];
                };
            };
            /** @description 缺少或无法解析认证态（`UNAUTHORIZED`） */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 跨租户访问被拒（`FORBIDDEN`，ADR-0003 §3.3 / M5 §3 验收 1） */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 上传文件超过 `MAX_UPLOAD_SIZE_MB`（`FILE_TOO_LARGE`，M1 验收 2） */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description MIME 不在白名单（`UNSUPPORTED_MEDIA_TYPE`，M1 验收 3） */
            415: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getDocumentGraph: {
        parameters: {
            query?: never;
            header?: {
                /** @description 【仅开发态兜底】租户 id。仅当 ALLOW_DEV_ORG_HEADER=true 且非生产环境时生效；Sprint 3 接入 M5 登录后必须移除（ADR-0003 §3.3：org_id 严禁来自 body / query）。 */
                "X-Org-Id"?: string | null;
                /** @description 【仅开发态兜底】操作者 id，缺省取 DEFAULT_ACTOR_ID；Sprint 3 起由认证态提供。 */
                "X-Actor-Id"?: string | null;
            };
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentGraphResponse"];
                };
            };
            /** @description 缺少或无法解析认证态（`UNAUTHORIZED`） */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 跨租户访问被拒（`FORBIDDEN`，ADR-0003 §3.3 / M5 §3 验收 1） */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 文档不存在（`DOCUMENT_NOT_FOUND`）。**跨租户访问返回 403 而非 404**（ADR-0003 / M5 §3 验收 1） */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 指定的 `kg_version` 非 active（`KG_VERSION_NOT_ACTIVE`）。**严禁静默降级**到最新 active 版本（ADR-0002 §3.2） */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 基础设施不可用（Neo4j 连接失败 / 查询超时，或 LLM 未配置、装配失败）时返回 501（`NOT_IMPLEMENTED`） */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getDocumentStatus: {
        parameters: {
            query?: never;
            header?: {
                /** @description 【仅开发态兜底】租户 id。仅当 ALLOW_DEV_ORG_HEADER=true 且非生产环境时生效；Sprint 3 接入 M5 登录后必须移除（ADR-0003 §3.3：org_id 严禁来自 body / query）。 */
                "X-Org-Id"?: string | null;
                /** @description 【仅开发态兜底】操作者 id，缺省取 DEFAULT_ACTOR_ID；Sprint 3 起由认证态提供。 */
                "X-Actor-Id"?: string | null;
            };
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentStatusResponse"];
                };
            };
            /** @description 缺少或无法解析认证态（`UNAUTHORIZED`） */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 跨租户访问被拒（`FORBIDDEN`，ADR-0003 §3.3 / M5 §3 验收 1） */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 文档不存在（`DOCUMENT_NOT_FOUND`）。**跨租户访问返回 403 而非 404**（ADR-0003 / M5 §3 验收 1） */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
}
