/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/agent/query": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 图谱问答
         * @description 单轮问答 + 可溯源引用。每个事实句必须能回溯到 `citations[]`，引用覆盖率不足时**必须拒答**（`refused = true`），严禁编造引用（M3 验收 3）。
         *
         *     `refused = true` 时 `answer` 恒为 `无法回答`。
         *
         *     **版本一致性（ADR-0002 §3.2）**：显式传入非 active 的 `kg_version` 时一律返回 **409** `KG_VERSION_NOT_ACTIVE`，**严禁静默降级**。
         *
         *     **实现状态**：已实装——由 `AgentService.query`（`app/services/agents.py`）执行「取 active 版本 → 拉取相关子图 → 加载 `kg_qa` Prompt → LLM 调用与解析」单轮链路，返回 `AgentQueryResponse`。
         *
         *     **501 `NOT_IMPLEMENTED` 的真实语义**：LLM 未配置（`LLM_API_KEY` 缺失）/ LangChain 装配失败 / Neo4j 不可用时返回 501，表示**基础设施不可用**，**不**表示「接口未实现」。
         */
        post: operations["queryAgent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 列出当前租户的文档（批次 C）
         * @description 按 `org_id` 强制过滤（ADR-0003），跨租户资源**永不**出现在结果里。
         *
         *     **查询参数**：
         *     - `q`：按 `filename_hash`（SHA-256 hex）前缀匹配。文件名原文**不**落库，演示场景下做「输入前缀」匹配即可。
         *     - `status`：可选 `pending / processing / completed / failed`。
         *     - `page`：1-based 页码，默认 1。
         *     - `page_size`：默认 10，**上限 100**（演示前端表格默认 10 条 / 页）。
         *
         *     **返回字段**：`filename` 字段展示的是 `filename_hash`（前端表格沿用 mock口径展示 hash，**不**伪造文件名原文，符合 M5 §4.5）；`entity_count` 仅当文档已参与建图（`kg_version_id IS NOT NULL`）时有值，否则为 `null`。
         *
         *     **一致性**：列表按 `created_at DESC` 排序（最新上传在前），PG 唯一真源；Neo4j 不可用时本接口仍可正常返回——不依赖图谱存储。
         */
        get: operations["listDocuments"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 上传文档（异步受理）
         * @description **同步校验 + 立即返回**，不在请求内做任何解析：
         *     1. MIME 白名单校验 → 失败 415；
         *     2. 大小上限校验（默认 100MB）→ 失败 413；
         *     3. 落 `documents` 记录（`status = pending`），注册 `document.parse` 异步执行体，并返回 `task_id`。
         *
         *     **解析链路**：执行体真实推进 `pending → processing → completed / failed`（M1 硬约束 H1），第三方 IO 异常按 H8 指数退避重试（≤ 3 次）；进程重启时由启动回收把在途任务置 `failed` + `error_code = TASK_INTERRUPTED`（ADR-0001 §3.2）。
         *
         *     上传响应的 `status` 恒为 `pending`，后续进度请轮询 `GET /documents/{id}/status`。
         *
         *     **当前局限**：状态机与错误落库为真实链路；MinerU 结构化解析与 LangExtract 实体关系抽取尚未接入，执行体当前返回空结果（后续版本补齐，见 v1.1.0 待办）。
         *
         *     文件名以 SHA-256 落库（`filename_hash`），日志与响应均不含原文。
         */
        post: operations["uploadDocument"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents/{document_id}/chunks/{chunk_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 按 chunk_id 回查原文片段（引用溯源）
         * @description 返回该文档下指定 `chunk_id` 的原文片段，供前端「点击引用标注 → 跳转到原文并高亮」（M3 §3 验收 2 / F3；Sprint 6 批次 B，Q2 拍板）；`Citation.snippet` 只带 ≤ 200 字摘录，chunk 全文**不**进引用体，故前端拿到 `Citation.char_offset` 后再按本端点取全文做高亮；数据源是批次 A 落盘的 `chunks.json`（存储层中间产物，位于 extract 段，与 Neo4j `:Chunk.text` 同源同值，**不**依赖图谱可用）；错误分支：文档不存在 → 404 `DOCUMENT_NOT_FOUND`，跨租户 → **403**（非 404，ADR-0003 / M5 §3 验收 1），产物缺失或其中无该 `chunk_id` → 404 `NOT_FOUND`。
         */
        get: operations["getDocumentChunk"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents/{document_id}/graph": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 获取文档图谱子图
         * @description 返回该文档在 Neo4j 中的子图（`nodes` + `edges`），供前端力导向图渲染。
         *
         *     **一致性（ADR-0002 §3.2）**：只返回 `status = active` 的 `kg_version`；该文档不存在 active 版本时返回 **409** `KG_VERSION_NOT_ACTIVE`，**绝不静默降级**到其他版本；响应中的 `version_status` 恒为 `active`。
         *
         *     规模上限对齐 M3 §3 验收 1：单次节点数 ≤ 500，超限 `truncated = true`。
         *
         *     **实现状态**：已实装——由 `GraphService.fetch_document_subgraph`（`app/services/graphs.py`）按 `kg_version` 查询 Neo4j 子图，并映射为 `DocumentGraphResponse`（`nodes` / `edges` / `truncated` / `version_status`）。
         *
         *     **501 `NOT_IMPLEMENTED` 的真实语义**：Neo4j 不可用（连接失败 / 查询超时 / 凭据错误）属**基础设施故障**，此时返回 501——**不**表示「接口未实现」。
         */
        get: operations["getDocumentGraph"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents/{document_id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 查询文档解析状态
         * @description 状态机严格限定为 `pending → processing → completed / failed`（M1 硬约束 H1）。
         *
         *     轮询建议：首次 2s，3 次后降为 10s。
         *
         *     **跨租户访问返回 403**（`FORBIDDEN`），不返回 404——按 M5 §3 验收 1 的显式要求。
         */
        get: operations["getDocumentStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/entities/{entity_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 获取实体详情（批次 C）
         * @description 返回单个实体的属性 + 出边邻居（≤ 50 条）：
         *     - `attributes`：Neo4j 节点属性（系统字段 `id` / `kg_version` / `org_id` / `pii_flags` 等已过滤）；
         *     - `relations`：实体的 1 跳出边（含 `target_id` / `target_name` / `relation` 三元组）。
         *
         *     **错误响应**：
         *     - 实体不属于当前 active `kg_version` → **404** `ENTITY_NOT_FOUND`；
         *     - Neo4j 不可用 / 无 active 版本 → **501** `NOT_IMPLEMENTED` 或 **409** `KG_VERSION_NOT_ACTIVE`；
         *     - 跨租户访问 → **403** `FORBIDDEN`（**不**走 404，避免混淆资源不存在与权限不足 —— M5 §3 验收 1）。
         */
        get: operations["getEntityDetail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/graph/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 获取全局图谱概览（批次 C）
         * @description 返回 active `kg_version` 的全局实体子图概览：
         *     - `nodes` / `edges` 轻量投影（供前端力导向图渲染）；
         *     - `doc_count` / `entity_count` / `relation_count` 三个统计值；
         *     - `truncated`：超过 500 节点上限时为 `true`，**前端必须禁用「全部展开」**；
         *
         *     **一致性（ADR-0002 §3.2）**：只读 active 版本，不存在 active 版本时返回 **409** `KG_VERSION_NOT_ACTIVE`，**严禁静默降级**到历史版本。
         */
        get: operations["getGraphOverview"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/graph/versions/{version}/activate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 激活指定 kg_version（Sprint 6.3）
         * @description 把指定版本置为**可消费**并同步 Neo4j 镜像。
         *
         *     **真源语义**：PG `kg_versions` 为真源，其「可消费」语义在本表中写作 `ready`；Neo4j `:KgVersion.status='active'` 只是镜像（`superseded` 同理）。两者在本响应中同时返回，避免前端误以为存在两个状态机。
         *
         *     **为什么需要显式激活（真机背景）**：建图流水线只把 PG 置 `ready`，没人同步 Neo4j 镜像，读侧于是长期命中旧导入版本。
         *
         *     **错误语义**：
         *     - 版本不存在（PG 查不到，或 Neo4j 无该版本图数据）→ **404** `NOT_FOUND`；
         *     - 版本为 `pending` / `building` / `failed` → **409** `KG_VERSION_NOT_ACTIVE`；
         *     - Neo4j 不可用 → **501** `NOT_IMPLEMENTED`。
         */
        post: operations["activateKgVersion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 健康检查（豁免租户上下文）
         * @description 不要求认证、不返回任何业务数据。
         *
         *     依赖异常时仍返回 **200**，仅把 `status` 降级为 `degraded`，避免负载均衡因单实例依赖抖动直接摘除全部流量。
         */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AgentQueryRequest
         * @description `POST /api/v1/agent/query` 请求体（M3 §4.1）。
         * @example {
         *       "kg_version": "20260320T1430Z-01H9X9ABCDEF",
         *       "question": "A 公司的子公司的供应商是否同时是 B 公司的股东？",
         *       "scope": "cross_doc"
         *     }
         */
        AgentQueryRequest: {
            /**
             * Doc Id
             * @description 限定文档 id，仅 `scope = single_doc` 时使用
             */
            doc_id?: string | null;
            /**
             * Kg Version
             * @description 指定图谱版本，缺省取最新 active 版本。若指定版本的 status ≠ active（writing / failed / superseded），一律返回 409 KG_VERSION_NOT_ACTIVE，严禁静默降级（ADR-0002 §3.2）
             */
            kg_version?: string | null;
            /**
             * Question
             * @description 用户问题（单轮，不做多轮上下文）
             */
            question: string;
            /**
             * Scope
             * @description 检索范围；`single_doc` 时 `doc_id` 必填
             * @default cross_doc
             * @enum {string}
             */
            scope: "single_doc" | "cross_doc";
        };
        /**
         * AgentQueryResponse
         * @description `POST /api/v1/agent/query` 响应（M3 §4.2）。
         *
         *     Sprint 4 阶段 10.0 批次 A 扩展（Sprint 3 缺口 1 偿还）：
         *     新增 ``kg_nodes`` / ``kg_relations`` / ``token_usage`` 三字段，
         *     供前端 p03「引用证据」面板展示图谱证据与 token 用量。
         * @example {
         *       "answer": "是。示例子公司 A 的供应商 C 同时持有 B 公司 12% 股权 [source: doc-9/page-3/chunk-12]",
         *       "citations": [
         *         {
         *           "char_offset": 480,
         *           "chunk_id": "chunk-12",
         *           "doc_id": "3f1a9c2e-7b45-4d8a-9e01-2c4f6a8b0d11",
         *           "page": 3,
         *           "snippet": "……供应商 C 持有本公司 12% 股权……"
         *         }
         *       ],
         *       "confidence": "high",
         *       "kg_nodes": [
         *         {
         *           "canonical_name": "示例科技有限公司",
         *           "confidence": 0.93,
         *           "entity_type": "公司",
         *           "id": "e-001",
         *           "kg_version": "20260320T1430Z-01H9X9ABCDEF",
         *           "label": "Entity"
         *         }
         *       ],
         *       "kg_relations": [
         *         {
         *           "id": "r-001",
         *           "properties": {
         *             "share_pct": 51
         *           },
         *           "source": "e-001",
         *           "target": "e-002",
         *           "type": "AFFILIATED_WITH"
         *         }
         *       ],
         *       "kg_version": "20260320T1430Z-01H9X9ABCDEF",
         *       "refused": false,
         *       "route": "m3_graphqa",
         *       "token_usage": {
         *         "completion_tokens": 256,
         *         "prompt_tokens": 2048,
         *         "total_tokens": 2304
         *       },
         *       "trace_id": "5f2c1b7e-9d4a-4c1e-8f3b-6a0d2e5c7b91"
         *     }
         */
        AgentQueryResponse: {
            /**
             * Answer
             * @description 答案文本，含 `[source: ...]` 标记；拒答时恒为 `"无法回答"`
             */
            answer: string;
            /**
             * Citations
             * @description 引用列表；`refused = false` 时必须覆盖全部事实句（覆盖率 100%）
             */
            citations: components["schemas"]["Citation"][];
            /**
             * Confidence
             * @description `low` 时前端必须标记「建议人工复核」（M3 §3 验收 6）
             * @enum {string}
             */
            confidence: "high" | "medium" | "low";
            /**
             * Kg Nodes
             * @description 支撑本次答案的图谱节点（复用 `DocumentGraphResponse.nodes` 同构模型）；拒答 / 图谱为空时为空列表
             */
            kg_nodes?: components["schemas"]["GraphNode"][];
            /**
             * Kg Relations
             * @description 支撑本次答案的图谱关系（复用 `DocumentGraphResponse.edges` 同构模型）；拒答 / 图谱为空时为空列表
             */
            kg_relations?: components["schemas"]["GraphEdge"][];
            /**
             * Kg Version
             * @description 本次检索实际使用的图谱版本（必为 active）
             */
            kg_version: string;
            /**
             * Refusal Reason
             * @description 仅 `refused = true` 时非空
             */
            refusal_reason?: ("no_grounded_evidence" | "out_of_scope" | "low_confidence") | null;
            /**
             * Refused
             * @description 是否拒答（严禁 LLM 编造引用，M3 §3 验收 3）
             */
            refused: boolean;
            /**
             * Route
             * @description 意图路由结果；`m4_affiliation` 表示已转交 M4 场景识别
             * @enum {string}
             */
            route: "m3_graphqa" | "m4_affiliation";
            /** @description LLM token 用量；拒答分支未调用 LLM、或 LLM 未返回 usage 时为 `null` */
            token_usage?: components["schemas"]["TokenUsage"] | null;
            /** Trace Id */
            trace_id: string;
        };
        /** Body_uploadDocument */
        Body_uploadDocument: {
            /**
             * File
             * @description 待解析文件。白名单：PDF / DOCX / CSV；单文件 ≤ 100MB
             */
            file: string;
        };
        /**
         * Citation
         * @description 引用条目：答案的每一个事实句都必须能回溯到此结构（M3 §4.2）。
         *
         *     引用覆盖率必须为 100%，否则必须拒答（反证条件 F3）。
         *
         *     **Sprint 6 批次 B（Q1 拍板）**：``page`` 改为 nullable——页码来自 MinerU
         *     ``content_list`` 文本对齐反推（批次 A 的 ``PageIndex``），
         *     **对齐失配时必须给 ``null``，严禁兜底伪造 1**。
         */
        Citation: {
            /**
             * Char Offset
             * @description 引用在 chunk 内的字符偏移。批次 B 为 chunk 起点（0）；实体级偏移待 `:Entity` 落 `char_start` 后细化
             */
            char_offset: number;
            /** Chunk Id */
            chunk_id: string;
            /**
             * Doc Id
             * Format: uuid
             */
            doc_id: string;
            /**
             * Page
             * @description 页码（1-based）；页码无法判定时为 `null`（严禁伪造）
             */
            page?: number | null;
            /**
             * Snippet
             * @description 用于 UI 高亮的原文片段（≤ 200 字的 chunk 摘录）
             */
            snippet: string;
        };
        /**
         * DocumentChunkResponse
         * @description `GET /api/v1/documents/{id}/chunks/{chunk_id}` 响应：单个原文片段。
         *
         *     **Q2 拍板**：溯源走**独立端点**回查原文，chunk 全文**不**塞进 `Citation`
         *     （`Citation.snippet` 只带 ≤ 200 字摘录），故前端点击引用标注时按
         *     `chunk_id` 取本响应，再按 `Citation.char_offset` 在 `text` 内高亮。
         *
         *     数据源：批次 A 落盘的 `chunks.json`（存储层中间产物，**不进契约**）；
         *     与 Neo4j `:Chunk` 同源同值，但不依赖图谱可用。
         * @example {
         *       "char_end": 764,
         *       "char_start": 0,
         *       "chunk_id": "chunk-581e8912827d",
         *       "doc_id": "3f1a9c2e-7b45-4d8a-9e01-2c4f6a8b0d11",
         *       "page": 1,
         *       "text": "甲方：北京青云科技有限公司（以下简称甲方）……",
         *       "trace_id": "5f2c1b7e-9d4a-4c1e-8f3b-6a0d2e5c7b91"
         *     }
         */
        DocumentChunkResponse: {
            /**
             * Char End
             * @description 片段在文档全文中的结束字符偏移（不含）
             */
            char_end: number;
            /**
             * Char Start
             * @description 片段在文档全文中的起始字符偏移（含）
             */
            char_start: number;
            /**
             * Chunk Id
             * @description 片段 id（`chunk-<12 hex>`）
             */
            chunk_id: string;
            /**
             * Doc Id
             * Format: uuid
             * @description 片段所属文档 id
             */
            doc_id: string;
            /**
             * Page
             * @description 页码（1-based）；页码无法判定时为 `null`
             */
            page?: number | null;
            /**
             * Text
             * @description 片段原文（前端高亮的定位基准）
             */
            text: string;
            /** Trace Id */
            trace_id: string;
        };
        /**
         * DocumentError
         * @description `documents.status = failed` 时的失败信息。
         *
         *     与顶层 `ErrorResponse` 的区别：这里**不含** `trace_id`，
         *     因为响应体已在外层携带同一个 `trace_id`。
         */
        DocumentError: {
            /** @description 失败错误码。进程重启回收的场景为 `TASK_INTERRUPTED`（ADR-0001 §3.2） */
            code: components["schemas"]["ErrorCode"];
            /**
             * Detail
             * @description 失败明细摘要。**禁止**回显 `documents.error_detail` 原文（敏感）
             */
            detail?: {
                [key: string]: unknown;
            } | null;
            /** Message */
            message: string;
        };
        /**
         * DocumentGraphResponse
         * @description `GET /api/v1/documents/{id}/graph` 响应：该文档在 Neo4j 中的子图。
         *
         *     **一致性约束（ADR-0002 §3.2）**：只返回 `status = active` 的 `kg_version`；
         *     该文档无 active 版本时返回 `409 KG_VERSION_NOT_ACTIVE`，**绝不静默降级**到其他版本。
         *
         *     规模上限对齐 M3 §3 验收 1：单次返回节点数 ≤ 500，超限时 `truncated = true`。
         * @example {
         *       "doc_id": "3f1a9c2e-7b45-4d8a-9e01-2c4f6a8b0d11",
         *       "edges": [
         *         {
         *           "id": "r-001",
         *           "properties": {
         *             "share_pct": 51,
         *             "since": "2021-03-01"
         *           },
         *           "source": "e-001",
         *           "target": "e-002",
         *           "type": "AFFILIATED_WITH"
         *         }
         *       ],
         *       "kg_version": "20260320T1430Z-01H9X9ABCDEF",
         *       "node_count": 1,
         *       "nodes": [
         *         {
         *           "canonical_name": "示例科技有限公司",
         *           "confidence": 0.93,
         *           "entity_type": "公司",
         *           "id": "e-001",
         *           "kg_version": "20260320T1430Z-01H9X9ABCDEF",
         *           "label": "Entity"
         *         }
         *       ],
         *       "relation_count": 1,
         *       "trace_id": "5f2c1b7e-9d4a-4c1e-8f3b-6a0d2e5c7b91",
         *       "truncated": false,
         *       "version_status": "active"
         *     }
         */
        DocumentGraphResponse: {
            /**
             * Doc Id
             * Format: uuid
             */
            doc_id: string;
            /** Edges */
            edges: components["schemas"]["GraphEdge"][];
            /**
             * Kg Version
             * @description 本次返回的图谱版本，来自 `GET /internal/kg/active` 的 active 版本
             */
            kg_version: string;
            /**
             * Node Count
             * @description `nodes` 实际条数（截断后）
             */
            node_count: number;
            /** Nodes */
            nodes: components["schemas"]["GraphNode"][];
            /**
             * Relation Count
             * @description `edges` 实际条数（截断后）
             */
            relation_count: number;
            /** Trace Id */
            trace_id: string;
            /**
             * Truncated
             * @description 是否因超过 500 节点上限被截断
             * @default false
             */
            truncated: boolean;
            /**
             * Version Status
             * @description 恒为 `active`，是 ADR-0002 一致性强制的可见契约
             * @constant
             */
            version_status: "active";
        };
        /**
         * DocumentListItem
         * @description `GET /documents` 单条结果。
         *
         *     字段对齐 `frontend/src/types/mock.d.ts::DocumentListItem`（Sprint 5 批次 C 收口），
         *     保证 `npm run gen:api` 生成的 TS 类型可直接替换前端 mock 类型。
         * @example {
         *       "entity_count": 128,
         *       "file_type": "PDF",
         *       "filename": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
         *       "id": "3f1a9c2e-7b45-4d8a-9e01-2c4f6a8b0d11",
         *       "status": "completed",
         *       "task_id": "3f1a9c2e-7b45-4d8a-9e01-2c4f6a8b0d11",
         *       "time_label": "10:42",
         *       "trace_id": "5f2c1b7e-9d4a-4c1e-8f3b-6a0d2e5c7b91",
         *       "uploaded_at": "2026-09-21T10:42:00Z"
         *     }
         */
        DocumentListItem: {
            /** Entity Count */
            entity_count?: number | null;
            /**
             * File Type
             * @description 文件类型标签
             * @enum {string}
             */
            file_type: "PDF" | "DOCX" | "CSV";
            /**
             * Filename
             * @description SHA-256(filename) — 文件名展示用
             */
            filename: string;
            /**
             * Id
             * Format: uuid
             * @description 文档主键 UUID
             */
            id: string;
            /**
             * Status
             * @description M1 状态机取值
             * @enum {string}
             */
            status: "pending" | "processing" | "completed" | "failed";
            /**
             * Task Id
             * Format: uuid
             * @description 任务 id，与 `documents.id` 一致
             */
            task_id: string;
            /**
             * Time Label
             * @description 相对时间文案，固定 UTC 计算
             */
            time_label: string;
            /**
             * Trace Id
             * @description 贯穿上传→解析→建图全链路的 trace_id
             */
            trace_id: string;
            /**
             * Uploaded At
             * @description ISO8601 上传时间（UTC）
             */
            uploaded_at: string;
        };
        /**
         * DocumentListResponse
         * @description `GET /documents` 响应。
         * @example {
         *       "items": [
         *         {
         *           "entity_count": 128,
         *           "file_type": "PDF",
         *           "filename": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
         *           "id": "3f1a9c2e-7b45-4d8a-9e01-2c4f6a8b0d11",
         *           "status": "completed",
         *           "task_id": "3f1a9c2e-7b45-4d8a-9e01-2c4f6a8b0d11",
         *           "time_label": "10:42",
         *           "trace_id": "5f2c1b7e-9d4a-4c1e-8f3b-6a0d2e5c7b91",
         *           "uploaded_at": "2026-09-21T10:42:00Z"
         *         }
         *       ],
         *       "page": 1,
         *       "page_size": 10,
         *       "total": 27,
         *       "trace_id": "5f2c1b7e-9d4a-4c1e-8f3b-6a0d2e5c7b91"
         *     }
         */
        DocumentListResponse: {
            /**
             * Items
             * @description 当前页结果
             */
            items: components["schemas"]["DocumentListItem"][];
            /**
             * Page
             * @description 当前页码（1-based）
             */
            page: number;
            /**
             * Page Size
             * @description 每页条目数（请求参数回显）
             */
            page_size: number;
            /**
             * Total
             * @description 当前租户下满足过滤条件的文档总数
             */
            total: number;
            /** Trace Id */
            trace_id: string;
        };
        /**
         * DocumentStatusResponse
         * @description `GET /api/v1/documents/{id}/status` 响应（M1 验收 5）。
         *
         *     前端轮询建议：首次 2s，3 次后降为 10s。
         * @example {
         *       "status": "processing",
         *       "task_id": "3f1a9c2e-7b45-4d8a-9e01-2c4f6a8b0d11",
         *       "trace_id": "5f2c1b7e-9d4a-4c1e-8f3b-6a0d2e5c7b91"
         *     }
         */
        DocumentStatusResponse: {
            /** @description 仅当 `status = failed` 时非空 */
            error?: components["schemas"]["DocumentError"] | null;
            /**
             * Progress
             * @description 0–1 的粗粒度进度。解析进度不可精确估计时为 `null`（Sprint 1 恒为 null）
             */
            progress?: number | null;
            /**
             * Status
             * @description 仅取 `pending / processing / completed / failed`（H1）
             * @enum {string}
             */
            status: "pending" | "processing" | "completed" | "failed";
            /**
             * Task Id
             * Format: uuid
             */
            task_id: string;
            /** Trace Id */
            trace_id: string;
        };
        /**
         * EntityAttribute
         * @description 实体详情属性项。
         */
        EntityAttribute: {
            /**
             * Label
             * @description 属性名（人类可读）
             */
            label: string;
            /**
             * Value
             * @description 属性值
             */
            value: string;
        };
        /**
         * EntityDetail
         * @description `GET /entities/{entity_id}` 响应：单个实体的属性 + 出边邻居。
         *
         *     邻居数上限由 ``settings`` 或路由层硬上限（默认 50）控制；
         *     跨租户访问 → 403 ``FORBIDDEN``；不存在 → 404 ``ENTITY_NOT_FOUND``。
         * @example {
         *       "attributes": [
         *         {
         *           "label": "首次出现",
         *           "value": "企业知识库架构设计.pdf"
         *         },
         *         {
         *           "label": "置信度",
         *           "value": "0.98"
         *         }
         *       ],
         *       "canonical_name": "数据安全合规",
         *       "category": "topic",
         *       "confidence": 0.98,
         *       "entity_type": "核心主题",
         *       "id": "e-001",
         *       "kg_version": "20260320T1430Z-01H9X9ABCDEF",
         *       "relation_count": 18,
         *       "relations": [
         *         {
         *           "relation": "包含",
         *           "target_id": "e-002",
         *           "target_name": "数据分级分类"
         *         }
         *       ],
         *       "trace_id": "5f2c1b7e-9d4a-4c1e-8f3b-6a0d2e5c7b91"
         *     }
         */
        EntityDetail: {
            /** Attributes */
            attributes: components["schemas"]["EntityAttribute"][];
            /**
             * Canonical Name
             * @description `:Entity.canonical_name`（消解后标准名）
             */
            canonical_name: string;
            /**
             * Category
             * @description 前端图例分类
             * @enum {string}
             */
            category: "topic" | "norm" | "org" | "system";
            /** Confidence */
            confidence?: number | null;
            /**
             * Entity Type
             * @description `:Entity.type`
             */
            entity_type: string;
            /**
             * Id
             * @description Neo4j `:Entity.id`
             */
            id: string;
            /**
             * Kg Version
             * @description active kg_version
             */
            kg_version: string;
            /**
             * Relation Count
             * @description 实体的总出度 + 入度
             */
            relation_count: number;
            /** Relations */
            relations: components["schemas"]["EntityRelation"][];
            /** Trace Id */
            trace_id: string;
        };
        /**
         * EntityRelation
         * @description 实体详情关系项。
         */
        EntityRelation: {
            /**
             * Relation
             * @description 关系名
             */
            relation: string;
            /**
             * Target Id
             * @description 目标实体 id
             */
            target_id: string;
            /**
             * Target Name
             * @description 目标实体名（前端直接展示）
             */
            target_name: string;
        };
        /**
         * ErrorCode
         * @description 统一业务错误码。HTTP 状态码与业务错误码分离（CODEBUDDY.md 错误响应规范）。
         * @enum {string}
         */
        ErrorCode: "VALIDATION_ERROR" | "UNAUTHORIZED" | "FORBIDDEN" | "NOT_FOUND" | "DOCUMENT_NOT_FOUND" | "ENTITY_NOT_FOUND" | "FILE_TOO_LARGE" | "UNSUPPORTED_MEDIA_TYPE" | "KG_VERSION_NOT_ACTIVE" | "KG_TENANT_LEAK" | "TASK_INTERRUPTED" | "NOT_IMPLEMENTED" | "INTERNAL_ERROR" | "HTTP_ERROR";
        /**
         * ErrorResponse
         * @description 统一错误响应体（**所有** 4xx / 5xx 均使用本结构）。
         *
         *     来源：`CODEBUDDY.md`「错误响应规范」。
         * @example {
         *       "code": "KG_VERSION_NOT_ACTIVE",
         *       "detail": {
         *         "kg_version": "20260320T1430Z-01H9X9",
         *         "version_status": "writing"
         *       },
         *       "message": "Requested kg_version is not active",
         *       "trace_id": "5f2c1b7e-9d4a-4c1e-8f3b-6a0d2e5c7b91"
         *     }
         */
        ErrorResponse: {
            /**
             * @description 业务错误码（HTTP 状态码与业务错误码分离）
             * @example VALIDATION_ERROR
             * @example FORBIDDEN
             * @example KG_VERSION_NOT_ACTIVE
             */
            code: components["schemas"]["ErrorCode"];
            /**
             * Detail
             * @description 结构化补充信息；敏感字段（文件名原文 / error_detail / pii_flags）严禁出现在此
             */
            detail?: {
                [key: string]: unknown;
            } | null;
            /**
             * Message
             * @description 面向调用方的简短英文摘要，便于日志检索
             */
            message: string;
            /**
             * Trace Id
             * @description 与响应头 X-Trace-Id 一致，贯穿 M1–M5 全链路
             */
            trace_id: string;
        };
        /** GraphEdge */
        GraphEdge: {
            /** Id */
            id: string;
            /**
             * Properties
             * @description 关系属性（如 `share_pct` / `since` / `amount` / `role`），不含证据原文
             */
            properties?: {
                [key: string]: unknown;
            };
            /**
             * Source
             * @description 起点节点 id
             */
            source: string;
            /**
             * Target
             * @description 终点节点 id
             */
            target: string;
            /**
             * Type
             * @description 关系类型（M2 §4.2），含桥梁抽取的实体↔实体类关系
             * @enum {string}
             */
            type: "HAS_CHUNK" | "MENTIONS" | "SUPPORTED_BY" | "AFFILIATED_WITH" | "SUPPLIES_TO" | "PARTY_TO" | "HAS_FINANCIAL_INDICATOR" | "OPERATES_SEGMENT" | "RELATED";
        };
        /**
         * GraphNode
         * @description 图谱节点。
         *
         *     **刻意不含** `pii_flags`：M2 §5.3 明确禁止该字段外泄。
         */
        GraphNode: {
            /**
             * Canonical Name
             * @description `:Entity.canonical_name`（消解后的标准名）
             */
            canonical_name?: string | null;
            /**
             * Confidence
             * @description 抽取置信度
             */
            confidence?: number | null;
            /**
             * Entity Type
             * @description `:Entity.type`（公司 / 自然人 / 法人 / 地址 / 证件号等）
             */
            entity_type?: string | null;
            /** Id */
            id: string;
            /**
             * Kg Version
             * @description 节点所属图谱版本，必须等于响应的 `kg_version`
             */
            kg_version: string;
            /**
             * Label
             * @enum {string}
             */
            label: "Document" | "Chunk" | "Entity" | "Evidence";
        };
        /**
         * GraphOverviewEdge
         * @description `GET /graph/overview` 边轻量投影。
         */
        GraphOverviewEdge: {
            /** Id */
            id: string;
            /**
             * Relation
             * @description 关系名（来自 Neo4j ``type(r)``）
             */
            relation: string;
            /**
             * Source
             * @description 起点节点 id
             */
            source: string;
            /**
             * Target
             * @description 终点节点 id
             */
            target: string;
        };
        /**
         * GraphOverviewNode
         * @description `GET /graph/overview` 节点轻量投影。
         *
         *     仅含前端力导向图渲染所需的最小字段集合，**不含** ``label`` /
         *     ``confidence`` / ``pii_flags`` 等（避免演示字段污染契约可溯源链）。
         */
        GraphOverviewNode: {
            /**
             * Category
             * @description 前端图例分类（4 类）
             * @enum {string}
             */
            category: "topic" | "norm" | "org" | "system";
            /**
             * Id
             * @description Neo4j 节点 id（`:Entity.id`）
             */
            id: string;
            /**
             * Name
             * @description `:Entity.canonical_name`
             */
            name: string;
            /** Seed X */
            seed_x: number;
            /** Seed Y */
            seed_y: number;
            /**
             * Type
             * @description `:Entity.type`（原始字符串）
             */
            type: string;
            /**
             * Weight
             * @description 相对权重，决定节点半径
             */
            weight: number;
        };
        /**
         * GraphOverviewResponse
         * @description `GET /graph/overview` 响应：全局图谱概览。
         *
         *     节点 / 边上限 500（与 ``DocumentGraphResponse`` 对齐），超限时
         *     ``truncated = true`` —— 前端禁用「全部展开」以避免误以为是真实全量。
         * @example {
         *       "doc_count": 27,
         *       "edges": [
         *         {
         *           "id": "r-001",
         *           "relation": "包含",
         *           "source": "e-001",
         *           "target": "e-002"
         *         }
         *       ],
         *       "entity_count": 1428,
         *       "kg_version": "20260320T1430Z-01H9X9ABCDEF",
         *       "nodes": [
         *         {
         *           "category": "topic",
         *           "id": "e-001",
         *           "name": "数据安全合规",
         *           "seed_x": 0.14,
         *           "seed_y": 0.38,
         *           "type": "核心主题",
         *           "weight": 1.65
         *         }
         *       ],
         *       "relation_count": 3604,
         *       "trace_id": "5f2c1b7e-9d4a-4c1e-8f3b-6a0d2e5c7b91",
         *       "truncated": false
         *     }
         */
        GraphOverviewResponse: {
            /**
             * Doc Count
             * @description 当前租户下有 active kg_version 的文档数
             */
            doc_count: number;
            /** Edges */
            edges: components["schemas"]["GraphOverviewEdge"][];
            /**
             * Entity Count
             * @description active kg_version 内的实体数（总）
             */
            entity_count: number;
            /**
             * Kg Version
             * @description active kg_version 版本号
             */
            kg_version: string;
            /** Nodes */
            nodes: components["schemas"]["GraphOverviewNode"][];
            /**
             * Relation Count
             * @description active kg_version 内的关系数（总）
             */
            relation_count: number;
            /** Trace Id */
            trace_id: string;
            /**
             * Truncated
             * @description 是否因超过 500 节点上限被截断
             * @default false
             */
            truncated: boolean;
        };
        /** HealthCheckStatus */
        HealthCheckStatus: {
            /**
             * Database
             * @description 数据库连通性。SQLite 兜底期间仅探测 `SELECT 1`，不代表 RLS 已生效
             * @enum {string}
             */
            database: "up" | "down";
        };
        /**
         * HealthResponse
         * @description 健康检查响应。
         *
         *     **本接口豁免租户上下文**：不要求认证、不返回任何业务数据。
         * @example {
         *       "checks": {
         *         "database": "up"
         *       },
         *       "status": "ok",
         *       "time": "2026-09-16T08:30:00Z",
         *       "trace_id": "5f2c1b7e-9d4a-4c1e-8f3b-6a0d2e5c7b91",
         *       "version": "1.0.0"
         *     }
         */
        HealthResponse: {
            checks: components["schemas"]["HealthCheckStatus"];
            /**
             * Status
             * @description `ok` = 全部依赖正常；`degraded` = 依赖异常但进程可服务（HTTP 仍为 200）
             * @enum {string}
             */
            status: "ok" | "degraded";
            /**
             * Time
             * Format: date-time
             * @description 服务端 UTC 时间
             */
            time: string;
            /** Trace Id */
            trace_id: string;
            /**
             * Version
             * @description 契约版本，与 openapi.yaml 的 info.version 一致
             */
            version: string;
        };
        /**
         * KgVersionActivationResponse
         * @description `POST /graph/versions/{version}/activate` 响应（Sprint 6.3）。
         *
         *     **两套词汇的显式映射（真机实测）**：PG ``kg_versions`` 为真源，用 ``ready``
         *     表达「可消费」；Neo4j ``:KgVersion`` 只是镜像，用 ``active`` 表达同一语义。
         *     两个字段同时返回，**不**合并成一个模糊的 ``status``，免得前端误以为存在
         *     两个不同的状态机。
         * @example {
         *       "activated_at": "2026-09-22T12:34:56.789012+00:00",
         *       "graph_mirror_status": "active",
         *       "source_status": "ready",
         *       "superseded_versions": [
         *         "20260917T090000Z-phase09"
         *       ],
         *       "trace_id": "5f2c1b7e-9d4a-4c1e-8f3b-6a0d2e5c7b91",
         *       "version": "v-3e381d36"
         *     }
         */
        KgVersionActivationResponse: {
            /**
             * Activated At
             * @description 激活时刻（UTC ISO-8601）
             */
            activated_at: string;
            /**
             * Graph Mirror Status
             * @description Neo4j `:KgVersion.status` 镜像值（恒为 `active`）
             */
            graph_mirror_status: string;
            /**
             * Source Status
             * @description PG 真源状态（active 语义在本表中写作 `ready`）
             */
            source_status: string;
            /**
             * Superseded Versions
             * @description 本次被置为 `superseded` 的历史版本（Neo4j 镜像侧；可为空）
             */
            superseded_versions?: string[];
            /** Trace Id */
            trace_id: string;
            /**
             * Version
             * @description 被激活的 kg_version 版本号
             */
            version: string;
        };
        /**
         * TokenUsage
         * @description LLM token 用量（对齐 DeepSeek / OpenAI 兼容 API 的 `usage` 格式）。
         *
         *     按「实测结果反哺规则」：骨架链路 / LLM 未返回 usage 时，
         *     上层字段 ``AgentQueryResponse.token_usage`` 置 ``null``，**严禁造数据**。
         */
        TokenUsage: {
            /**
             * Completion Tokens
             * @description 输出 token 数
             * @default 0
             */
            completion_tokens: number;
            /**
             * Prompt Tokens
             * @description 输入 token 数
             * @default 0
             */
            prompt_tokens: number;
            /**
             * Total Tokens
             * @description 总 token 数
             * @default 0
             */
            total_tokens: number;
        };
        /**
         * UploadResponse
         * @description `POST /api/v1/documents/upload` 响应（M1 验收 1）。
         * @example {
         *       "status": "pending",
         *       "task_id": "3f1a9c2e-7b45-4d8a-9e01-2c4f6a8b0d11",
         *       "trace_id": "5f2c1b7e-9d4a-4c1e-8f3b-6a0d2e5c7b91"
         *     }
         */
        UploadResponse: {
            /**
             * Status
             * @description 上传受理后恒为 `pending`（异步执行）
             * @constant
             */
            status: "pending";
            /**
             * Task Id
             * Format: uuid
             * @description 任务 id（UUIDv4），与 `documents.id` 一致；M2 抽取任务复用同一 id 空间
             */
            task_id: string;
            /** Trace Id */
            trace_id: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    queryAgent: {
        parameters: {
            query?: never;
            header?: {
                /** @description 【仅开发态兜底】租户 id。仅当 ALLOW_DEV_ORG_HEADER=true 且非生产环境时生效；Sprint 3 接入 M5 登录后必须移除（ADR-0003 §3.3：org_id 严禁来自 body / query）。 */
                "X-Org-Id"?: string | null;
                /** @description 【仅开发态兜底】操作者 id，缺省取 DEFAULT_ACTOR_ID；Sprint 3 起由认证态提供。 */
                "X-Actor-Id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AgentQueryRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentQueryResponse"];
                };
            };
            /** @description 请求校验失败（`VALIDATION_ERROR`），`detail.errors` 给出字段级原因 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 缺少或无法解析认证态（`UNAUTHORIZED`） */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 403 跨租户拒绝，两种成因：① `FORBIDDEN`（ADR-0003 §3.3）——请求资源 org_id 不符；② `KG_TENANT_LEAK`（ADR-0003 §4，Sprint 5 批次 B）——fail-closed 校验发现 active kg_version 内存在不属于当前 org 的节点，属数据质量事故伪装为正常结论，**不**降级为拒答（200） */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 指定的 `kg_version` 非 active（`KG_VERSION_NOT_ACTIVE`）。**严禁静默降级**到最新 active 版本（ADR-0002 §3.2） */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 基础设施不可用（Neo4j 连接失败 / 查询超时，或 LLM 未配置、装配失败）时返回 501（`NOT_IMPLEMENTED`） */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    listDocuments: {
        parameters: {
            query?: {
                /** @description 按 `filename_hash` 前缀匹配（SHA-256 hex）。示例：`q=e3b0` 匹配 hash 以 `e3b0` 开头的所有文档 */
                q?: string | null;
                /** @description 按状态过滤；M1 H1 状态机取值之一 */
                status?: string | null;
                /** @description 1-based 页码 */
                page?: number;
                /** @description 每页条目数（默认 10，上限 100） */
                page_size?: number;
            };
            header?: {
                /** @description 【仅开发态兜底】租户 id。仅当 ALLOW_DEV_ORG_HEADER=true 且非生产环境时生效；Sprint 3 接入 M5 登录后必须移除（ADR-0003 §3.3：org_id 严禁来自 body / query）。 */
                "X-Org-Id"?: string | null;
                /** @description 【仅开发态兜底】操作者 id，缺省取 DEFAULT_ACTOR_ID；Sprint 3 起由认证态提供。 */
                "X-Actor-Id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentListResponse"];
                };
            };
            /** @description 请求校验失败（`VALIDATION_ERROR`），`detail.errors` 给出字段级原因 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 缺少或无法解析认证态（`UNAUTHORIZED`） */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 跨租户访问被拒（`FORBIDDEN`，ADR-0003 §3.3 / M5 §3 验收 1） */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    uploadDocument: {
        parameters: {
            query?: never;
            header?: {
                /** @description 【仅开发态兜底】租户 id。仅当 ALLOW_DEV_ORG_HEADER=true 且非生产环境时生效；Sprint 3 接入 M5 登录后必须移除（ADR-0003 §3.3：org_id 严禁来自 body / query）。 */
                "X-Org-Id"?: string | null;
                /** @description 【仅开发态兜底】操作者 id，缺省取 DEFAULT_ACTOR_ID；Sprint 3 起由认证态提供。 */
                "X-Actor-Id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_uploadDocument"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadResponse"];
                };
            };
            /** @description 缺少或无法解析认证态（`UNAUTHORIZED`） */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 跨租户访问被拒（`FORBIDDEN`，ADR-0003 §3.3 / M5 §3 验收 1） */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 上传文件超过 `MAX_UPLOAD_SIZE_MB`（`FILE_TOO_LARGE`，M1 验收 2） */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description MIME 不在白名单（`UNSUPPORTED_MEDIA_TYPE`，M1 验收 3） */
            415: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getDocumentChunk: {
        parameters: {
            query?: never;
            header?: {
                /** @description 【仅开发态兜底】租户 id。仅当 ALLOW_DEV_ORG_HEADER=true 且非生产环境时生效；Sprint 3 接入 M5 登录后必须移除（ADR-0003 §3.3：org_id 严禁来自 body / query）。 */
                "X-Org-Id"?: string | null;
                /** @description 【仅开发态兜底】操作者 id，缺省取 DEFAULT_ACTOR_ID；Sprint 3 起由认证态提供。 */
                "X-Actor-Id"?: string | null;
            };
            path: {
                document_id: string;
                chunk_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentChunkResponse"];
                };
            };
            /** @description 缺少或无法解析认证态（`UNAUTHORIZED`） */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 跨租户访问被拒（`FORBIDDEN`，ADR-0003 §3.3 / M5 §3 验收 1） */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 原文片段不存在（`NOT_FOUND`）：该文档尚未产出 `chunks.json`，或其中没有该 `chunk_id`。**跨租户访问返回 403 而非 404**（ADR-0003 / M5 §3 验收 1） */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getDocumentGraph: {
        parameters: {
            query?: never;
            header?: {
                /** @description 【仅开发态兜底】租户 id。仅当 ALLOW_DEV_ORG_HEADER=true 且非生产环境时生效；Sprint 3 接入 M5 登录后必须移除（ADR-0003 §3.3：org_id 严禁来自 body / query）。 */
                "X-Org-Id"?: string | null;
                /** @description 【仅开发态兜底】操作者 id，缺省取 DEFAULT_ACTOR_ID；Sprint 3 起由认证态提供。 */
                "X-Actor-Id"?: string | null;
            };
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentGraphResponse"];
                };
            };
            /** @description 缺少或无法解析认证态（`UNAUTHORIZED`） */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 跨租户访问被拒（`FORBIDDEN`，ADR-0003 §3.3 / M5 §3 验收 1） */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 文档不存在（`DOCUMENT_NOT_FOUND`）。**跨租户访问返回 403 而非 404**（ADR-0003 / M5 §3 验收 1） */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 指定的 `kg_version` 非 active（`KG_VERSION_NOT_ACTIVE`）。**严禁静默降级**到最新 active 版本（ADR-0002 §3.2） */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 基础设施不可用（Neo4j 连接失败 / 查询超时，或 LLM 未配置、装配失败）时返回 501（`NOT_IMPLEMENTED`） */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getDocumentStatus: {
        parameters: {
            query?: never;
            header?: {
                /** @description 【仅开发态兜底】租户 id。仅当 ALLOW_DEV_ORG_HEADER=true 且非生产环境时生效；Sprint 3 接入 M5 登录后必须移除（ADR-0003 §3.3：org_id 严禁来自 body / query）。 */
                "X-Org-Id"?: string | null;
                /** @description 【仅开发态兜底】操作者 id，缺省取 DEFAULT_ACTOR_ID；Sprint 3 起由认证态提供。 */
                "X-Actor-Id"?: string | null;
            };
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentStatusResponse"];
                };
            };
            /** @description 缺少或无法解析认证态（`UNAUTHORIZED`） */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 跨租户访问被拒（`FORBIDDEN`，ADR-0003 §3.3 / M5 §3 验收 1） */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 文档不存在（`DOCUMENT_NOT_FOUND`）。**跨租户访问返回 403 而非 404**（ADR-0003 / M5 §3 验收 1） */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getEntityDetail: {
        parameters: {
            query?: never;
            header?: {
                /** @description 【仅开发态兜底】租户 id。仅当 ALLOW_DEV_ORG_HEADER=true 且非生产环境时生效；Sprint 3 接入 M5 登录后必须移除（ADR-0003 §3.3：org_id 严禁来自 body / query）。 */
                "X-Org-Id"?: string | null;
                /** @description 【仅开发态兜底】操作者 id，缺省取 DEFAULT_ACTOR_ID；Sprint 3 起由认证态提供。 */
                "X-Actor-Id"?: string | null;
            };
            path: {
                entity_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EntityDetail"];
                };
            };
            /** @description 缺少或无法解析认证态（`UNAUTHORIZED`） */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 403 跨租户拒绝，两种成因：① `FORBIDDEN`（ADR-0003 §3.3）——请求资源 org_id 不符；② `KG_TENANT_LEAK`（ADR-0003 §4，Sprint 5 批次 B）——fail-closed 校验发现 active kg_version 内存在不属于当前 org 的节点，属数据质量事故伪装为正常结论，**不**降级为拒答（200） */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 实体不存在（`ENTITY_NOT_FOUND`）。**跨租户访问返回 403 而非 404**（ADR-0003 / M5 §3 验收 1；Sprint 5 批次 C） */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 指定的 `kg_version` 非 active（`KG_VERSION_NOT_ACTIVE`）。**严禁静默降级**到最新 active 版本（ADR-0002 §3.2） */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 基础设施不可用（Neo4j 连接失败 / 查询超时，或 LLM 未配置、装配失败）时返回 501（`NOT_IMPLEMENTED`） */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getGraphOverview: {
        parameters: {
            query?: never;
            header?: {
                /** @description 【仅开发态兜底】租户 id。仅当 ALLOW_DEV_ORG_HEADER=true 且非生产环境时生效；Sprint 3 接入 M5 登录后必须移除（ADR-0003 §3.3：org_id 严禁来自 body / query）。 */
                "X-Org-Id"?: string | null;
                /** @description 【仅开发态兜底】操作者 id，缺省取 DEFAULT_ACTOR_ID；Sprint 3 起由认证态提供。 */
                "X-Actor-Id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GraphOverviewResponse"];
                };
            };
            /** @description 缺少或无法解析认证态（`UNAUTHORIZED`） */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 403 跨租户拒绝，两种成因：① `FORBIDDEN`（ADR-0003 §3.3）——请求资源 org_id 不符；② `KG_TENANT_LEAK`（ADR-0003 §4，Sprint 5 批次 B）——fail-closed 校验发现 active kg_version 内存在不属于当前 org 的节点，属数据质量事故伪装为正常结论，**不**降级为拒答（200） */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 指定的 `kg_version` 非 active（`KG_VERSION_NOT_ACTIVE`）。**严禁静默降级**到最新 active 版本（ADR-0002 §3.2） */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 基础设施不可用（Neo4j 连接失败 / 查询超时，或 LLM 未配置、装配失败）时返回 501（`NOT_IMPLEMENTED`） */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    activateKgVersion: {
        parameters: {
            query?: never;
            header?: {
                /** @description 【仅开发态兜底】租户 id。仅当 ALLOW_DEV_ORG_HEADER=true 且非生产环境时生效；Sprint 3 接入 M5 登录后必须移除（ADR-0003 §3.3：org_id 严禁来自 body / query）。 */
                "X-Org-Id"?: string | null;
                /** @description 【仅开发态兜底】操作者 id，缺省取 DEFAULT_ACTOR_ID；Sprint 3 起由认证态提供。 */
                "X-Actor-Id"?: string | null;
            };
            path: {
                version: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KgVersionActivationResponse"];
                };
            };
            /** @description 缺少或无法解析认证态（`UNAUTHORIZED`） */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 跨租户访问被拒（`FORBIDDEN`，ADR-0003 §3.3 / M5 §3 验收 1） */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 指定的 `kg_version` 不存在（`NOT_FOUND`）：PG `kg_versions` 真源表中查不到该 (org_id, version)，或 Neo4j 侧没有该版本的图数据。复用`ErrorCode.NOT_FOUND`，**不**新增错误码。 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 指定的 `kg_version` 非 active（`KG_VERSION_NOT_ACTIVE`）。**严禁静默降级**到最新 active 版本（ADR-0002 §3.2） */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 基础设施不可用（Neo4j 连接失败 / 查询超时，或 LLM 未配置、装配失败）时返回 501（`NOT_IMPLEMENTED`） */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
}
