"""baseline sprint1-9.5 tables

Revision ID: 00f44b912817
Revises:
Create Date: 2026-09-28 15:50:27.625529

**基线迁移（D-2，Sprint 9.7 H1）**：从零建出截至 Sprint 9.5 的全部 10 张表
（含 ADR-0004 登记的预留字段，如 ``documents.source_type`` / ``acl_scope`` /
``content_hash`` 与 ``external_refs`` 表——只落库、不进 API 契约）。

- 由空库 autogenerate 产生并**逐字审阅**：表 / 列 / 索引 / 约束与
  ``app.db.models.Base.metadata`` 一致（等价性由
  ``tests/test_migrations_baseline.py`` 机械钉死，今后加表忘写迁移 CI 必红）；
- 与 ``create_all`` 的关系：后者保留为 dev / 测试兜底（启动行为不变），
  生产升级按 ``docs/deployment-spec.md`` §7.2 手动 ``alembic upgrade head``。
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00f44b912817'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('affiliation_suspicions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('task_id', sa.Uuid(), nullable=False),
    sa.Column('suspicion_type', sa.String(length=32), nullable=False),
    sa.Column('severity', sa.String(length=8), nullable=False),
    sa.Column('entities', sa.JSON(), nullable=False),
    sa.Column('entity_names', sa.JSON(), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('causes', sa.JSON(), nullable=True),
    sa.Column('kg_version', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('reviewed_by', sa.Uuid(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('trace_id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("severity IN ('high', 'medium', 'low')", name='ck_affiliation_suspicions_severity'),
    sa.CheckConstraint("status IN ('open', 'dismissed', 'confirmed')", name='ck_affiliation_suspicions_status'),
    sa.CheckConstraint("suspicion_type IN ('shared_legal_rep', 'shared_address', 'missing_check_in')", name='ck_affiliation_suspicions_type'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_affiliation_suspicions_org_id'), 'affiliation_suspicions', ['org_id'], unique=False)
    op.create_index('ix_affiliation_suspicions_org_id_created_at', 'affiliation_suspicions', ['org_id', 'created_at'], unique=False)
    op.create_index('ix_affiliation_suspicions_org_id_status', 'affiliation_suspicions', ['org_id', 'status'], unique=False)
    op.create_index('ix_affiliation_suspicions_org_id_task_id', 'affiliation_suspicions', ['org_id', 'task_id'], unique=False)
    op.create_index(op.f('ix_affiliation_suspicions_trace_id'), 'affiliation_suspicions', ['trace_id'], unique=False)
    op.create_table('affiliation_tasks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('doc_ids', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('error_detail', sa.Text(), nullable=True),
    sa.Column('result_summary', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('trace_id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("status IN ('pending', 'processing', 'completed', 'failed')", name='ck_affiliation_tasks_status'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_affiliation_tasks_org_id'), 'affiliation_tasks', ['org_id'], unique=False)
    op.create_index('ix_affiliation_tasks_org_id_created_at', 'affiliation_tasks', ['org_id', 'created_at'], unique=False)
    op.create_index('ix_affiliation_tasks_org_id_status', 'affiliation_tasks', ['org_id', 'status'], unique=False)
    op.create_index(op.f('ix_affiliation_tasks_trace_id'), 'affiliation_tasks', ['trace_id'], unique=False)
    op.create_table('audit_log',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('action', sa.String(length=255), nullable=False),
    sa.Column('actor_id', sa.Uuid(), nullable=True),
    sa.Column('actor_ip', sa.String(length=64), nullable=True),
    sa.Column('doc_id', sa.Uuid(), nullable=True),
    sa.Column('resource', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('trace_id', sa.Uuid(), nullable=False),
    sa.Column('detail', sa.JSON(), nullable=True),
    sa.CheckConstraint("status IN ('success', 'failure')", name='ck_audit_log_status'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_org_id'), 'audit_log', ['org_id'], unique=False)
    op.create_index('ix_audit_log_org_id_action', 'audit_log', ['org_id', 'action'], unique=False)
    op.create_index('ix_audit_log_org_id_status', 'audit_log', ['org_id', 'status'], unique=False)
    op.create_index('ix_audit_log_org_id_trace_id', 'audit_log', ['org_id', 'trace_id'], unique=False)
    op.create_index('ix_audit_log_org_id_ts', 'audit_log', ['org_id', 'ts'], unique=False)
    op.create_index(op.f('ix_audit_log_trace_id'), 'audit_log', ['trace_id'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('filename_hash', sa.String(length=64), nullable=False),
    sa.Column('mime_type', sa.String(length=255), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('uploaded_by', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('storage_key', sa.Text(), nullable=True),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('error_detail', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source_type', sa.String(length=32), nullable=True),
    sa.Column('source_ref', sa.String(length=255), nullable=True),
    sa.Column('document_key', sa.String(length=255), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('source_version', sa.String(length=64), nullable=True),
    sa.Column('acl_scope', sa.String(length=64), nullable=True),
    sa.Column('acl_owner_ref', sa.String(length=255), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('trace_id', sa.Uuid(), nullable=False),
    sa.Column('extract_status', sa.String(length=16), nullable=True),
    sa.Column('extract_retry_count', sa.Integer(), nullable=False),
    sa.Column('kg_build_status', sa.String(length=16), nullable=True),
    sa.Column('kg_build_retry_count', sa.Integer(), nullable=False),
    sa.Column('kg_version_id', sa.Uuid(), nullable=True),
    sa.CheckConstraint("status IN ('pending', 'processing', 'completed', 'failed')", name='ck_documents_status'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_filename_hash'), 'documents', ['filename_hash'], unique=False)
    op.create_index(op.f('ix_documents_org_id'), 'documents', ['org_id'], unique=False)
    op.create_index('ix_documents_org_id_created_at', 'documents', ['org_id', 'created_at'], unique=False)
    op.create_index('ix_documents_org_id_status', 'documents', ['org_id', 'status'], unique=False)
    op.create_index(op.f('ix_documents_trace_id'), 'documents', ['trace_id'], unique=False)
    op.create_index(op.f('ix_documents_uploaded_by'), 'documents', ['uploaded_by'], unique=False)
    op.create_table('domain_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('event_type', sa.String(length=32), nullable=False),
    sa.Column('aggregate_type', sa.String(length=64), nullable=False),
    sa.Column('aggregate_id', sa.String(length=255), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('trace_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('dispatched_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("event_type IN ('document.parsed', 'kg.updated', 'risk.suspect_created', 'qa.answered')", name='ck_domain_events_event_type'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_domain_events_org_id'), 'domain_events', ['org_id'], unique=False)
    op.create_index('ix_domain_events_org_id_created_at', 'domain_events', ['org_id', 'created_at'], unique=False)
    op.create_index('ix_domain_events_org_id_event_type', 'domain_events', ['org_id', 'event_type'], unique=False)
    op.create_index(op.f('ix_domain_events_trace_id'), 'domain_events', ['trace_id'], unique=False)
    op.create_table('external_refs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('object_type', sa.String(length=16), nullable=False),
    sa.Column('local_id', sa.String(length=255), nullable=False),
    sa.Column('external_system', sa.String(length=32), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("object_type IN ('entity', 'document', 'org')", name='ck_external_refs_object_type'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_external_refs_org_id'), 'external_refs', ['org_id'], unique=False)
    op.create_index('ix_external_refs_org_id_object_type', 'external_refs', ['org_id', 'object_type'], unique=False)
    op.create_index('ux_external_refs_org_sys_ext', 'external_refs', ['org_id', 'external_system', 'external_id'], unique=True)
    op.create_table('kg_versions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('source_doc_ids', sa.JSON(), nullable=False),
    sa.Column('entity_count', sa.Integer(), nullable=False),
    sa.Column('relation_count', sa.Integer(), nullable=False),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('error_detail', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ready_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('trace_id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("status IN ('pending', 'building', 'ready', 'failed')", name='ck_kg_versions_status'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kg_versions_org_id'), 'kg_versions', ['org_id'], unique=False)
    op.create_index('ix_kg_versions_org_id_created_at', 'kg_versions', ['org_id', 'created_at'], unique=False)
    op.create_index('ix_kg_versions_org_id_status', 'kg_versions', ['org_id', 'status'], unique=False)
    op.create_index(op.f('ix_kg_versions_trace_id'), 'kg_versions', ['trace_id'], unique=False)
    op.create_table('ontology_schemas',
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('entity_types', sa.JSON(), nullable=False),
    sa.Column('relation_types', sa.JSON(), nullable=False),
    sa.Column('domain_description', sa.Text(), nullable=False),
    sa.Column('suggested_by_llm', sa.Boolean(), nullable=False),
    sa.Column('confirmed_by_user', sa.Uuid(), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('trace_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('active', 'superseded')", name='ck_ontology_schemas_status'),
    sa.PrimaryKeyConstraint('org_id', 'version')
    )
    op.create_index(op.f('ix_ontology_schemas_confirmed_by_user'), 'ontology_schemas', ['confirmed_by_user'], unique=False)
    op.create_index('ix_ontology_schemas_org_id_created_at', 'ontology_schemas', ['org_id', 'created_at'], unique=False)
    op.create_index('ix_ontology_schemas_org_id_status', 'ontology_schemas', ['org_id', 'status'], unique=False)
    op.create_index(op.f('ix_ontology_schemas_trace_id'), 'ontology_schemas', ['trace_id'], unique=False)
    op.create_table('qa_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('question_hash', sa.String(length=64), nullable=False),
    sa.Column('answer_hash', sa.String(length=64), nullable=False),
    sa.Column('citation_count', sa.Integer(), nullable=False),
    sa.Column('refused', sa.Boolean(), nullable=False),
    sa.Column('refusal_reason', sa.String(length=64), nullable=True),
    sa.Column('kg_version', sa.String(length=64), nullable=False),
    sa.Column('trace_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_qa_logs_org_id'), 'qa_logs', ['org_id'], unique=False)
    op.create_index('ix_qa_logs_org_id_created_at', 'qa_logs', ['org_id', 'created_at'], unique=False)
    op.create_index('ix_qa_logs_org_id_trace_id', 'qa_logs', ['org_id', 'trace_id'], unique=False)
    op.create_index(op.f('ix_qa_logs_trace_id'), 'qa_logs', ['trace_id'], unique=False)
    op.create_table('unaligned_subjects',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('raw_name', sa.Text(), nullable=False),
    sa.Column('source_doc_id', sa.Uuid(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('candidates', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('pending', 'aligned', 'ignored')", name='ck_unaligned_subjects_status'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_unaligned_subjects_org_id'), 'unaligned_subjects', ['org_id'], unique=False)
    op.create_index('ix_unaligned_subjects_org_id_created_at', 'unaligned_subjects', ['org_id', 'created_at'], unique=False)
    op.create_index('ix_unaligned_subjects_org_id_status', 'unaligned_subjects', ['org_id', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_unaligned_subjects_org_id_status', table_name='unaligned_subjects')
    op.drop_index('ix_unaligned_subjects_org_id_created_at', table_name='unaligned_subjects')
    op.drop_index(op.f('ix_unaligned_subjects_org_id'), table_name='unaligned_subjects')
    op.drop_table('unaligned_subjects')
    op.drop_index(op.f('ix_qa_logs_trace_id'), table_name='qa_logs')
    op.drop_index('ix_qa_logs_org_id_trace_id', table_name='qa_logs')
    op.drop_index('ix_qa_logs_org_id_created_at', table_name='qa_logs')
    op.drop_index(op.f('ix_qa_logs_org_id'), table_name='qa_logs')
    op.drop_table('qa_logs')
    op.drop_index(op.f('ix_ontology_schemas_trace_id'), table_name='ontology_schemas')
    op.drop_index('ix_ontology_schemas_org_id_status', table_name='ontology_schemas')
    op.drop_index('ix_ontology_schemas_org_id_created_at', table_name='ontology_schemas')
    op.drop_index(op.f('ix_ontology_schemas_confirmed_by_user'), table_name='ontology_schemas')
    op.drop_table('ontology_schemas')
    op.drop_index(op.f('ix_kg_versions_trace_id'), table_name='kg_versions')
    op.drop_index('ix_kg_versions_org_id_status', table_name='kg_versions')
    op.drop_index('ix_kg_versions_org_id_created_at', table_name='kg_versions')
    op.drop_index(op.f('ix_kg_versions_org_id'), table_name='kg_versions')
    op.drop_table('kg_versions')
    op.drop_index('ux_external_refs_org_sys_ext', table_name='external_refs')
    op.drop_index('ix_external_refs_org_id_object_type', table_name='external_refs')
    op.drop_index(op.f('ix_external_refs_org_id'), table_name='external_refs')
    op.drop_table('external_refs')
    op.drop_index(op.f('ix_domain_events_trace_id'), table_name='domain_events')
    op.drop_index('ix_domain_events_org_id_event_type', table_name='domain_events')
    op.drop_index('ix_domain_events_org_id_created_at', table_name='domain_events')
    op.drop_index(op.f('ix_domain_events_org_id'), table_name='domain_events')
    op.drop_table('domain_events')
    op.drop_index(op.f('ix_documents_uploaded_by'), table_name='documents')
    op.drop_index(op.f('ix_documents_trace_id'), table_name='documents')
    op.drop_index('ix_documents_org_id_status', table_name='documents')
    op.drop_index('ix_documents_org_id_created_at', table_name='documents')
    op.drop_index(op.f('ix_documents_org_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_filename_hash'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_audit_log_trace_id'), table_name='audit_log')
    op.drop_index('ix_audit_log_org_id_ts', table_name='audit_log')
    op.drop_index('ix_audit_log_org_id_trace_id', table_name='audit_log')
    op.drop_index('ix_audit_log_org_id_status', table_name='audit_log')
    op.drop_index('ix_audit_log_org_id_action', table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_org_id'), table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index(op.f('ix_affiliation_tasks_trace_id'), table_name='affiliation_tasks')
    op.drop_index('ix_affiliation_tasks_org_id_status', table_name='affiliation_tasks')
    op.drop_index('ix_affiliation_tasks_org_id_created_at', table_name='affiliation_tasks')
    op.drop_index(op.f('ix_affiliation_tasks_org_id'), table_name='affiliation_tasks')
    op.drop_table('affiliation_tasks')
    op.drop_index(op.f('ix_affiliation_suspicions_trace_id'), table_name='affiliation_suspicions')
    op.drop_index('ix_affiliation_suspicions_org_id_task_id', table_name='affiliation_suspicions')
    op.drop_index('ix_affiliation_suspicions_org_id_status', table_name='affiliation_suspicions')
    op.drop_index('ix_affiliation_suspicions_org_id_created_at', table_name='affiliation_suspicions')
    op.drop_index(op.f('ix_affiliation_suspicions_org_id'), table_name='affiliation_suspicions')
    op.drop_table('affiliation_suspicions')
    # ### end Alembic commands ###
