"""add relation_expiry_policies (ADR-0005 L1)

Revision ID: 4e7759c33526
Revises: 7989c2c821da
Create Date: 2026-09-28 16:50:34.540409

**S9 批次 B：CP-T1 冻结的第 3 条在这里落地**。表回答「某个 ``relation_type``
是否只允许一个当前值」：``single_current``（法定代表人 / 注册地址，新事实封旧）
/ ``append_only``（对外投资等天然多值，仲裁跳过）；``relation_type = '*'``
是该租户的兜底行，连兜底行都没有时按并存处理。

autogenerate 产物已人工审阅：``create_table`` 一条 + 索引一条，
``downgrade`` 对称可回；唯一约束 ``(org_id, relation_type)`` 与 CheckConstraint
两档都按 ORM 落位。它是 ``app.services.kg.policies.load_expiry_policies``
的唯一数据源——**没有那处的读取，本表就是无消费者的死表**。
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e7759c33526'
down_revision: Union[str, Sequence[str], None] = '7989c2c821da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('relation_expiry_policies',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('relation_type', sa.String(length=64), nullable=False),
    sa.Column('policy', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("policy IN ('single_current', 'append_only')", name='ck_relation_expiry_policies_policy'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'relation_type', name='uq_relation_expiry_policies_org_type')
    )
    op.create_index('ix_relation_expiry_policies_org_id', 'relation_expiry_policies', ['org_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_relation_expiry_policies_org_id', table_name='relation_expiry_policies')
    op.drop_table('relation_expiry_policies')
    # ### end Alembic commands ###
