"""add documents.document_date (ADR-0005 L0)

Revision ID: 7989c2c821da
Revises: 00f44b912817
Create Date: 2026-09-28 16:11:15.572483

**S9 批次 A：CP-T1 冻结后的第一次增量迁移**——给 ``documents`` 加 ``document_date``
（``Date``、可空）。ADR-0005 §4 / §6 L0 要求：文档日期是关系 ``valid_from`` 的
**兜底源**（R4 不猜值——文本无显式日期时取它，不代填、不推断）；可空是因为并非
每份文档都有可识别日期（假日期比没有日期危险）。

autogenerate 产物已人工审阅：只一条 ``add_column``，``downgrade`` 对称可回。
这也是 Sprint 9.7 建立的“加列忘写迁移 ⇒ 等价性测试必红”纪律首次实战。
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7989c2c821da'
down_revision: Union[str, Sequence[str], None] = '00f44b912817'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('document_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'document_date')
    # ### end Alembic commands ###
